-- Fix create_group function to accept is_public parameter
-- This should be applied to fix the RPC error

DROP FUNCTION IF EXISTS create_group(TEXT, INTEGER, TEXT);
DROP FUNCTION IF EXISTS create_group(TEXT, INTEGER, TEXT, BOOLEAN);

CREATE OR REPLACE FUNCTION create_group(
    p_name TEXT,
    p_created_by INTEGER,
    p_description TEXT DEFAULT '',
    p_is_public BOOLEAN DEFAULT false
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_group_id INTEGER;
    result JSON;
BEGIN
    -- Check if created_by is allowed to create groups
    IF p_created_by < 2 THEN
        RAISE EXCEPTION 'Users with ID less than 2 are not allowed to create groups';
    END IF;
    
    -- Validate group name
    IF p_name IS NULL OR trim(p_name) = '' THEN
        RAISE EXCEPTION 'Group name is required' USING ERRCODE = '23514';
    END IF;
    
    -- Check if user exists
    IF NOT EXISTS (SELECT 1 FROM users WHERE user_id = p_created_by) THEN
        RAISE EXCEPTION 'Creator user with ID % not found', p_created_by USING ERRCODE = 'P0002';
    END IF;
    
    -- Insert new group (invite_code will be auto-generated by trigger)
    INSERT INTO groups (name, description, created_by, is_public, created_at)
    VALUES (p_name, p_description, p_created_by, p_is_public, NOW())
    RETURNING group_id INTO v_group_id;
    
    -- Add creator as admin member
    INSERT INTO group_participants (group_id, user_id, role, joined_at)
    VALUES (v_group_id, p_created_by, 'admin', NOW());
    
    -- Return success result with group details
    SELECT json_build_object(
        'success', true,
        'group_id', v_group_id,
        'name', p_name,
        'description', p_description,
        'is_public', p_is_public,
        'created_by', p_created_by,
        'created_at', NOW()
    ) INTO result;
    
    RETURN result;
EXCEPTION
    WHEN OTHERS THEN
        -- Return error result
        RETURN json_build_object(
            'success', false,
            'error', SQLERRM
        );
END;
$$;
