-- Fix timestamp type mismatch in create_group function
-- Migration: 20240920000003_fix_create_group_timestamp.sql

-- Update the create_group function to fix timestamp type mismatch
CREATE OR REPLACE FUNCTION create_group(
    p_name TEXT,
    p_created_by INTEGER,
    p_description TEXT DEFAULT '',
    p_is_public BOOLEAN DEFAULT false
)
RETURNS TABLE (
    group_id INTEGER,
    name TEXT,
    description TEXT,
    is_public BOOLEAN,
    invite_code TEXT,
    member_count BIGINT,
    created_at TIMESTAMP
) 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_group_id INTEGER;
    v_invite_code TEXT;
    v_created_at TIMESTAMP;
BEGIN
    -- Validate group name
    IF p_name IS NULL OR trim(p_name) = '' THEN
        RAISE EXCEPTION 'Group name is required' USING ERRCODE = '23514';
    END IF;
    
    -- Check if user exists
    IF NOT EXISTS (SELECT 1 FROM users WHERE user_id = p_created_by) THEN
        RAISE EXCEPTION 'Creator user with ID % not found', p_created_by USING ERRCODE = 'P0002';
    END IF;
    
    -- Insert new group (invite_code will be auto-generated by trigger)
    INSERT INTO groups (name, created_by, description, is_public)
    VALUES (p_name, p_created_by, COALESCE(p_description, ''), COALESCE(p_is_public, false))
    RETURNING groups.group_id, groups.invite_code, groups.created_at INTO v_group_id, v_invite_code, v_created_at;
    
    -- Add creator as admin member
    INSERT INTO group_participants (group_id, user_id, role)
    VALUES (v_group_id, p_created_by, 'admin');
    
    -- Return the created group
    RETURN QUERY
    SELECT 
        v_group_id as group_id,
        p_name as name,
        COALESCE(p_description, '') as description,
        COALESCE(p_is_public, false) as is_public,
        v_invite_code as invite_code,
        1::BIGINT as member_count,
        v_created_at as created_at;
END;
$$;