-- =====================================================
-- CORE SCHEMA INITIALIZATION
-- Date: 2024-09-16
-- Description: Initialize all core tables with proper relationships and constraints
-- =====================================================

-- Drop tables in reverse dependency order to avoid foreign key constraint errors
DROP TABLE IF EXISTS ai_metadata CASCADE;
DROP TABLE IF EXISTS session_papers CASCADE;
DROP TABLE IF EXISTS paper_tags CASCADE;
DROP TABLE IF EXISTS papers CASCADE;
DROP TABLE IF EXISTS feedback CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS session_participants CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS group_participants CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- =====================================================
-- USERS TABLE - Core user management with auth integration
-- =====================================================
CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id UUID UNIQUE,
    email TEXT NOT NULL UNIQUE,
    first_name TEXT,
    last_name TEXT,
    profile_picture_url TEXT,
    bio TEXT,
    phone_number TEXT,
    availability VARCHAR(50) DEFAULT 'available',
    provider TEXT DEFAULT 'google',
    provider_id TEXT,
    last_sign_in_at TIMESTAMP,
    raw_app_meta_data JSONB,
    raw_user_meta_data JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT availability_constraint CHECK (availability IN ('available', 'busy', 'offline')),
    CONSTRAINT check_guest_user_email CHECK (
        (user_id = 0 AND email = 'guest@system.local') OR 
        (user_id != 0 AND email != 'guest@system.local')
    )
);

-- Create indexes for users table
CREATE INDEX IF NOT EXISTS idx_users_auth_user_id ON users(auth_user_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- =====================================================
-- GROUPS TABLE - Group management with invite codes
-- =====================================================
CREATE TABLE groups (
    group_id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    invite_code VARCHAR(12) UNIQUE NOT NULL,
    is_public BOOLEAN DEFAULT false,
    created_by INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT check_group_creator_id CHECK (created_by >= 2)
);

-- Create indexes for groups table
CREATE INDEX IF NOT EXISTS idx_groups_created_by ON groups(created_by);
CREATE INDEX IF NOT EXISTS idx_groups_invite_code ON groups(invite_code);
CREATE INDEX IF NOT EXISTS idx_groups_name ON groups(name);

-- =====================================================
-- GROUP PARTICIPANTS - Group membership management
-- =====================================================
CREATE TABLE group_participants (
    group_participant_id SERIAL PRIMARY KEY,
    group_id INT NOT NULL REFERENCES groups(group_id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    role VARCHAR(50) NOT NULL,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(group_id, user_id),
    CONSTRAINT role_constraint CHECK (role IN ('admin', 'member', 'mentor'))
);

-- Create indexes for group_participants table
CREATE INDEX IF NOT EXISTS idx_group_participants_group_id ON group_participants(group_id);
CREATE INDEX IF NOT EXISTS idx_group_participants_user_id ON group_participants(user_id);

-- =====================================================
-- SESSIONS TABLE - Session management
-- =====================================================
CREATE TABLE sessions (
    session_id SERIAL PRIMARY KEY,
    group_id INT NOT NULL REFERENCES groups(group_id) ON DELETE CASCADE,
    created_by INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    topic TEXT,
    status VARCHAR(50) DEFAULT 'offline',
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMP,
    CONSTRAINT status_constraint CHECK (status IN ('offline', 'active', 'completed'))
);

-- Create indexes for sessions table
CREATE INDEX IF NOT EXISTS idx_sessions_group_id ON sessions(group_id);
CREATE INDEX IF NOT EXISTS idx_sessions_created_by ON sessions(created_by);
CREATE INDEX IF NOT EXISTS idx_sessions_status ON sessions(status);

-- =====================================================
-- SESSION PARTICIPANTS - Session membership
-- =====================================================
CREATE TABLE session_participants (
    session_id INT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(session_id, user_id)
);

-- Create indexes for session_participants table
CREATE INDEX IF NOT EXISTS idx_session_participants_session_id ON session_participants(session_id);
CREATE INDEX IF NOT EXISTS idx_session_participants_user_id ON session_participants(user_id);

-- =====================================================
-- MESSAGES TABLE - Chat messages
-- =====================================================
CREATE TABLE messages (
    message_id SERIAL PRIMARY KEY,
    session_id INT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    sender_id INT NOT NULL REFERENCES group_participants(group_participant_id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for messages table
CREATE INDEX IF NOT EXISTS idx_messages_session_id ON messages(session_id);
CREATE INDEX IF NOT EXISTS idx_messages_sender_id ON messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_messages_sent_at ON messages(sent_at);

-- =====================================================
-- PAPERS TABLE - Research paper management
-- =====================================================
CREATE TABLE papers (
    paper_id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    abstract TEXT,
    authors TEXT,
    doi TEXT UNIQUE,
    published_at TIMESTAMP,
    source_url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for papers table
CREATE INDEX IF NOT EXISTS idx_papers_title ON papers(title);
CREATE INDEX IF NOT EXISTS idx_papers_doi ON papers(doi);
CREATE INDEX IF NOT EXISTS idx_papers_published_at ON papers(published_at);

-- =====================================================
-- PAPER TAGS - Paper categorization
-- =====================================================
CREATE TABLE paper_tags (
    paper_id INT NOT NULL REFERENCES papers(paper_id) ON DELETE CASCADE,
    tag VARCHAR(100) NOT NULL,
    PRIMARY KEY (paper_id, tag)
);

-- Create indexes for paper_tags table
CREATE INDEX IF NOT EXISTS idx_paper_tags_paper_id ON paper_tags(paper_id);
CREATE INDEX IF NOT EXISTS idx_paper_tags_tag ON paper_tags(tag);

-- =====================================================
-- SESSION PAPERS - Papers associated with sessions
-- =====================================================
CREATE TABLE session_papers (
    session_id INT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    paper_id INT NOT NULL REFERENCES papers(paper_id) ON DELETE CASCADE,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(session_id, paper_id)
);

-- Create indexes for session_papers table
CREATE INDEX IF NOT EXISTS idx_session_papers_session_id ON session_papers(session_id);
CREATE INDEX IF NOT EXISTS idx_session_papers_paper_id ON session_papers(paper_id);

-- =====================================================
-- AI METADATA - AI interaction metadata
-- =====================================================
CREATE TABLE ai_metadata (
    id SERIAL PRIMARY KEY,
    page_no INTEGER,
    message_id INT NOT NULL REFERENCES messages(message_id) ON DELETE CASCADE,
    paper_id INT NOT NULL REFERENCES papers(paper_id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for ai_metadata table
CREATE INDEX IF NOT EXISTS idx_ai_metadata_message_id ON ai_metadata(message_id);
CREATE INDEX IF NOT EXISTS idx_ai_metadata_paper_id ON ai_metadata(paper_id);

-- =====================================================
-- FEEDBACK TABLE - User feedback on sessions
-- =====================================================
CREATE TABLE feedback (
    feedback_id SERIAL PRIMARY KEY,
    session_id INT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    given_by INT NOT NULL REFERENCES group_participants(group_participant_id) ON DELETE CASCADE,
    content TEXT,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for feedback table
CREATE INDEX IF NOT EXISTS idx_feedback_session_id ON feedback(session_id);
CREATE INDEX IF NOT EXISTS idx_feedback_given_by ON feedback(given_by);
CREATE INDEX IF NOT EXISTS idx_feedback_rating ON feedback(rating);

-- =====================================================
-- INITIAL DATA SETUP
-- =====================================================

-- Create guest user (ID 0)
INSERT INTO users (user_id, email, first_name, last_name, auth_user_id, created_at, updated_at)
VALUES (0, 'guest@system.local', 'Guest', 'User', '00000000-0000-0000-0000-000000000000', NOW(), NOW())
ON CONFLICT (user_id) DO NOTHING;

-- Create AI user (ID 1)
INSERT INTO users (user_id, email, first_name, last_name, created_at, updated_at)
VALUES (1, 'ai@assistant.com', 'AI', 'Assistant', NOW(), NOW())
ON CONFLICT (user_id) DO NOTHING;

-- Restart the identity sequence to ensure new users start from ID 2
SELECT setval('users_user_id_seq', GREATEST(2, (SELECT COALESCE(MAX(user_id), 1) FROM users WHERE user_id > 1)), true);

-- Add table comments for documentation
COMMENT ON TABLE users IS 'User ID 0 is reserved for guest users. User ID 1 is reserved for AI user. Users with ID < 2 cannot create groups.';
COMMENT ON COLUMN groups.invite_code IS 'Unique 8-character invite code for joining the group';
COMMENT ON COLUMN groups.description IS 'Optional description of the group';
COMMENT ON COLUMN groups.is_public IS 'Whether the group is publicly discoverable and joinable';
COMMENT ON CONSTRAINT check_group_creator_id ON groups IS 'Prevents guest users (ID < 2) from creating groups';