-- =====================================================
-- RECREATE GROUP MANAGEMENT FUNCTIONS
-- Date: 2024-10-01
-- Description: Group CRUD operations and group membership management
-- =====================================================

-- Create group function
CREATE OR REPLACE FUNCTION public.create_group(p_name text, p_created_by integer, p_description text DEFAULT ''::text, p_is_public boolean DEFAULT false)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
    v_group_id INTEGER;
    v_invite_code VARCHAR(12);
    result JSON;
BEGIN
    -- Check if created_by is allowed to create groups
    IF p_created_by < 2 THEN
        RAISE EXCEPTION 'Users with ID less than 2 are not allowed to create groups';
    END IF;
    
    -- Validate group name
    IF p_name IS NULL OR trim(p_name) = '' THEN
        RAISE EXCEPTION 'Group name is required' USING ERRCODE = '23514';
    END IF;
    
    -- Check if user exists
    IF NOT EXISTS (SELECT 1 FROM users WHERE user_id = p_created_by) THEN
        RAISE EXCEPTION 'Creator user with ID % not found', p_created_by USING ERRCODE = 'P0002';
    END IF;
    
    -- Insert new group (invite_code will be auto-generated by trigger)
    INSERT INTO groups (name, description, created_by, is_public, created_at)
    VALUES (p_name, p_description, p_created_by, p_is_public, NOW())
    RETURNING group_id, invite_code INTO v_group_id, v_invite_code;
    
    -- Add creator as admin member
    INSERT INTO group_participants (group_id, user_id, role, joined_at)
    VALUES (v_group_id, p_created_by, 'admin', NOW());
    
    -- Return success result with group details including invite_code
    SELECT json_build_object(
        'success', true,
        'group_id', v_group_id,
        'name', p_name,
        'description', p_description,
        'is_public', p_is_public,
        'invite_code', v_invite_code,
        'created_by', p_created_by,
        'created_at', NOW()
    ) INTO result;
    
    RETURN result;
EXCEPTION
    WHEN OTHERS THEN
        RAISE EXCEPTION 'Failed to create group: %', SQLERRM;
END;
$function$;

-- Get group by ID
CREATE OR REPLACE FUNCTION public.get_group_by_id(p_group_id integer)
RETURNS TABLE(id integer, name text, description text, member_count bigint, created_at timestamp without time zone)
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
    RETURN QUERY
    SELECT 
        g.group_id::INTEGER as id,
        g.name,
        COALESCE(g.description, '') as description,
        COUNT(gp.user_id) as member_count,
        g.created_at
    FROM groups g
    LEFT JOIN group_participants gp ON g.group_id = gp.group_id
    WHERE g.group_id = p_group_id
    GROUP BY g.group_id, g.name, g.description, g.created_at;
    
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Group with ID % not found', p_group_id USING ERRCODE = 'P0002';
    END IF;
END;
$function$;

-- Get group by name
CREATE OR REPLACE FUNCTION public.get_group_by_name(p_name text)
RETURNS TABLE(id integer, name text)
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
    RETURN QUERY
    SELECT 
        g.group_id::INTEGER as id,
        g.name
    FROM groups g
    WHERE LOWER(g.name) = LOWER(p_name)
    LIMIT 1;
    
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Group with name ''%'' not found', p_name USING ERRCODE = 'P0002';
    END IF;
END;
$function$;

-- Get all groups
CREATE OR REPLACE FUNCTION public.get_all_groups()
RETURNS TABLE(id integer, name text, description text, member_count bigint, created_at timestamp without time zone)
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
    RETURN QUERY
    SELECT 
        g.group_id::INTEGER as id,
        g.name,
        COALESCE(g.description, '') as description,
        COUNT(gp.user_id) as member_count,
        g.created_at
    FROM groups g
    LEFT JOIN group_participants gp ON g.group_id = gp.group_id
    GROUP BY g.group_id, g.name, g.description, g.created_at
    ORDER BY g.group_id;
END;
$function$;

-- Add group member
CREATE OR REPLACE FUNCTION public.add_group_member(p_group_id integer, p_user_id integer, p_role text DEFAULT 'member'::text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
    -- Check if group exists
    IF NOT EXISTS (SELECT 1 FROM groups g WHERE g.group_id = p_group_id) THEN
        RAISE EXCEPTION 'Group with ID % not found', p_group_id USING ERRCODE = 'P0002';
    END IF;
    
    -- Check if user exists
    IF NOT EXISTS (SELECT 1 FROM users u WHERE u.user_id = p_user_id) THEN
        RAISE EXCEPTION 'User with ID % not found', p_user_id USING ERRCODE = 'P0002';
    END IF;
    
    -- Check if user is already a member
    IF EXISTS (SELECT 1 FROM group_participants WHERE group_id = p_group_id AND user_id = p_user_id) THEN
        RAISE EXCEPTION 'User % is already a member of group %', p_user_id, p_group_id USING ERRCODE = '23505';
    END IF;
    
    -- Validate role
    IF p_role NOT IN ('admin', 'member', 'mentor') THEN
        RAISE EXCEPTION 'Invalid role. Must be admin, member, or mentor' USING ERRCODE = '23514';
    END IF;
    
    -- Add user to group
    INSERT INTO group_participants (group_id, user_id, role)
    VALUES (p_group_id, p_user_id, p_role);
    
    RETURN json_build_object('message', 'User ' || p_user_id || ' added to group ' || p_group_id);
END;
$function$;

-- Remove group member
CREATE OR REPLACE FUNCTION public.remove_group_member(p_group_id integer, p_user_id integer)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
    v_deleted_count INTEGER;
BEGIN
    -- Check if group exists
    IF NOT EXISTS (SELECT 1 FROM groups g WHERE g.group_id = p_group_id) THEN
        RAISE EXCEPTION 'Group with ID % not found', p_group_id USING ERRCODE = 'P0002';
    END IF;
    
    -- Remove user from group
    DELETE FROM group_participants 
    WHERE group_id = p_group_id AND user_id = p_user_id;
    
    GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
    
    IF v_deleted_count = 0 THEN
        RAISE EXCEPTION 'User % is not a member of group %', p_user_id, p_group_id USING ERRCODE = 'P0002';
    END IF;
    
    RETURN true;
END;
$function$;

-- Get group members (simple)
CREATE OR REPLACE FUNCTION public.get_group_members(p_group_id integer)
RETURNS TABLE(group_id integer, member_ids integer[], member_count bigint)
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
    v_member_ids INTEGER[];
    v_count BIGINT;
BEGIN
    -- Check if group exists
    IF NOT EXISTS (SELECT 1 FROM groups g WHERE g.group_id = p_group_id) THEN
        RAISE EXCEPTION 'Group with ID % not found', p_group_id USING ERRCODE = 'P0002';
    END IF;
    
    -- Get member IDs
    SELECT ARRAY_AGG(gp.user_id), COUNT(gp.user_id)
    INTO v_member_ids, v_count
    FROM group_participants gp
    WHERE gp.group_id = p_group_id;
    
    RETURN QUERY
    SELECT 
        p_group_id as group_id,
        COALESCE(v_member_ids, ARRAY[]::INTEGER[]) as member_ids,
        COALESCE(v_count, 0) as member_count;
END;
$function$;

-- Get group members (detailed)
CREATE OR REPLACE FUNCTION public.get_group_members_detailed(p_group_id integer)
RETURNS TABLE(user_id integer, name text, email text, role character varying, joined_at timestamp without time zone, is_active boolean, first_name text, last_name text)
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
    -- Check if group exists
    IF NOT EXISTS (SELECT 1 FROM groups WHERE group_id = p_group_id) THEN
        RAISE EXCEPTION 'Group with ID % not found', p_group_id USING ERRCODE = 'P0002';
    END IF;

    RETURN QUERY
    SELECT 
        u.user_id,
        COALESCE(
            TRIM(CONCAT(u.first_name, ' ', u.last_name)), 
            u.email
        ) as name,
        u.email,
        gp.role,
        gp.joined_at,
        CASE WHEN u.availability = 'available' THEN true ELSE false END as is_active,
        u.first_name,
        u.last_name
    FROM group_participants gp
    INNER JOIN users u ON gp.user_id = u.user_id
    WHERE gp.group_id = p_group_id
    ORDER BY gp.joined_at ASC;
END;
$function$;

-- Join group by invite code
CREATE OR REPLACE FUNCTION public.join_group_by_invite_code(p_invite_code text, p_user_id integer)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
    v_group_id INTEGER;
BEGIN
    -- Find group by invite code
    SELECT g.group_id INTO v_group_id
    FROM groups g
    WHERE g.invite_code = p_invite_code;
    
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Invalid invite code' USING ERRCODE = 'P0002';
    END IF;
    
    -- Check if user exists
    IF NOT EXISTS (SELECT 1 FROM users WHERE user_id = p_user_id) THEN
        RAISE EXCEPTION 'User with ID % not found', p_user_id USING ERRCODE = 'P0002';
    END IF;
    
    -- Check if user is already a member
    IF EXISTS (SELECT 1 FROM group_participants WHERE group_id = v_group_id AND user_id = p_user_id) THEN
        RAISE EXCEPTION 'User is already a member of this group' USING ERRCODE = '23505';
    END IF;
    
    -- Add user to group
    INSERT INTO group_participants (group_id, user_id, role)
    VALUES (v_group_id, p_user_id, 'member');
    
    RETURN json_build_object(
        'success', true,
        'message', 'Successfully joined group',
        'group_id', v_group_id
    );
END;
$function$;

-- Grant permissions
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO authenticated;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO anon;

-- Add comments
COMMENT ON FUNCTION public.create_group(text, integer, text, boolean) IS 'Creates a new group with invite code';
COMMENT ON FUNCTION public.get_group_by_id(integer) IS 'Retrieves group details by ID';
COMMENT ON FUNCTION public.get_group_by_name(text) IS 'Retrieves group by name';
COMMENT ON FUNCTION public.get_all_groups() IS 'Returns all groups with member counts';
COMMENT ON FUNCTION public.add_group_member(integer, integer, text) IS 'Adds a user to a group with specified role';
COMMENT ON FUNCTION public.remove_group_member(integer, integer) IS 'Removes a user from a group';
COMMENT ON FUNCTION public.get_group_members(integer) IS 'Returns group member IDs and count';
COMMENT ON FUNCTION public.get_group_members_detailed(integer) IS 'Returns detailed group member information';
COMMENT ON FUNCTION public.join_group_by_invite_code(text, integer) IS 'Allows user to join group using invite code';

-- =====================================================
-- VERIFICATION MESSAGE
-- =====================================================

DO $$
BEGIN
    RAISE NOTICE '✅ GROUP MANAGEMENT FUNCTIONS CREATED';
    RAISE NOTICE '📝 Ready for session management functions';
END $$;
