-- Migration: Add guest user and group creation restrictions
-- Created: 2025-09-19

-- First, we need to modify the users table to allow manual insertion of user_id 0
-- Temporarily change the identity column to allow manual override
ALTER TABLE users ALTER COLUMN user_id DROP IDENTITY IF EXISTS;
ALTER TABLE users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Now create the guest user with ID 0
INSERT INTO users (user_id, email, first_name, last_name, auth_user_id, created_at, updated_at)
VALUES (0, 'guest@system.local', 'Guest', 'User', '00000000-0000-0000-0000-000000000000', NOW(), NOW())
ON CONFLICT (user_id) DO NOTHING;

-- Restart the identity sequence to ensure new users start from ID 1
-- Find the current maximum user_id and restart sequence
SELECT setval('users_user_id_seq', GREATEST(1, (SELECT COALESCE(MAX(user_id), 0) FROM users WHERE user_id > 0)), true);

-- Add a check constraint to prevent users with ID < 2 from creating groups
-- This constraint will be enforced at the database level
ALTER TABLE groups ADD CONSTRAINT check_group_creator_id 
CHECK (created_by >= 2);

-- Update the create_group function to include the check
-- Note: This function only works with existing columns in the groups table
CREATE OR REPLACE FUNCTION create_group(
    p_name VARCHAR(255),
    p_created_by INTEGER
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_group_id INTEGER;
    result JSON;
BEGIN
    -- Check if created_by is allowed to create groups
    IF p_created_by < 2 THEN
        RAISE EXCEPTION 'Users with ID less than 2 are not allowed to create groups';
    END IF;

    -- Verify creator exists
    IF NOT EXISTS (SELECT 1 FROM users WHERE user_id = p_created_by) THEN
        RAISE EXCEPTION 'Creator user does not exist';
    END IF;
    
    -- Insert new group
    INSERT INTO groups (name, created_by, created_at)
    VALUES (p_name, p_created_by, NOW())
    RETURNING group_id INTO v_group_id;
    
    -- Add creator as first participant with admin role
    INSERT INTO group_participants (group_id, user_id, role, joined_at)
    VALUES (v_group_id, p_created_by, 'admin', NOW());
    
    -- Return success result with group details
    SELECT json_build_object(
        'success', true,
        'group_id', v_group_id,
        'name', p_name,
        'created_by', p_created_by,
        'created_at', NOW()
    ) INTO result;
    
    RETURN result;
EXCEPTION
    WHEN OTHERS THEN
        -- Return error result
        RETURN json_build_object(
            'success', false,
            'error', SQLERRM
        );
END;
$$;

-- Also add a trigger to enforce the constraint on any direct inserts
CREATE OR REPLACE FUNCTION check_group_creation_permissions()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.created_by < 2 THEN
        RAISE EXCEPTION 'Users with ID less than 2 are not allowed to create groups';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_check_group_creation_permissions
    BEFORE INSERT ON groups
    FOR EACH ROW
    EXECUTE FUNCTION check_group_creation_permissions();

-- Update the users table to ensure we have proper constraints
-- Make sure user_id 0 is reserved for guest
ALTER TABLE users ADD CONSTRAINT check_guest_user_email 
CHECK (
    (user_id = 0 AND email = 'guest@system.local') OR 
    (user_id != 0 AND email != 'guest@system.local')
);

-- Add a comment to explain the system
COMMENT ON TABLE users IS 'User ID 0 is reserved for guest users. User ID 1 is reserved for the first real user. Users with ID < 2 cannot create groups.';
COMMENT ON CONSTRAINT check_group_creator_id ON groups IS 'Prevents guest users (ID < 2) from creating groups';